apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-api
spec:
  template:
    spec:
      containers:
        - name: app
          image: 381491947495.dkr.ecr.ap-southeast-2.amazonaws.com/travel-api:c543121a
          env:
            - name: NODE_ENV
              value: test
