apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: soap-rest-api
    path: soap-rest-api.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: travel-api
    path: travel-api.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: travel-bff
    path: travel-bff.yaml
  - target:
      kind: Route
      name: hotel-bff
    path: hotel-bff-route.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: travel-ui
    path: travel-ui.yaml
  - target:
      kind: Route
      name: hotel-ui
    path: hotel-ui-route.yaml
