apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-ui
spec:
  template:
    spec:
      containers:
        - name: app
          image: 381491947495.dkr.ecr.ap-southeast-2.amazonaws.com/travel-ui:36288706-main
          env:
            - name: NODE_ENV
              value: test
