apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hotels
spec:
  host: hotels.yourcluster.example.com
  to:
    kind: Service
    name: travel-ui
    weight: 100
  port:
    targetPort: 3000
  wildcardPolicy: None
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
