apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-bff
spec:
  selector:
    matchLabels:
      app: travel-bff
  template:
    metadata:
      labels:
        app: travel-bff
    spec:
      containers:
        - name: app
          image: 381491947495.dkr.ecr.ap-southeast-2.amazonaws.com/travel-bff:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: travel-bff
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: travel-bff

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: travel-bff
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travel-bff
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 66

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hotel-bff
spec:
  host: hotel-bff.yourcluster.example.com
  # path: /search
  to:
    kind: Service
    name: travel-bff
    weight: 100
